name: Create Release Branch and PR

on:
  workflow_dispatch:

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: develop  # Ensure the workflow runs from the develop branch

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Read package.json version
        id: read_version
        run: |
          version=$(node -p "require('./package.json').version")
          major=$(echo $version | cut -d. -f1)
          minor=$(echo $version | cut -d. -f2)
          patch=$(echo $version | cut -d. -f3 | cut -d- -f1)
          new_minor=$((minor + 1))
          new_version="${major}.${new_minor}.0"
          echo "New version: $new_version"
          echo "::set-output name=version::$new_version"

      - name: Create new branch
        id: create_branch
        run: |
          new_version=${{ steps.read_version.outputs.version }}
          git checkout -b release/v$new_version
          git push origin release/v$new_version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Create release branch release/v${{ steps.read_version.outputs.version }}'
          branch: release/v${{ steps.read_version.outputs.version }}
          base: deploy
          title: 'Release v${{ steps.read_version.outputs.version }}'
          body: 'This PR is for the release of version ${{ steps.read_version.outputs.version }}'
