name: Build on Release Branch Merged into Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - release/v*

jobs:
  build_on_merge:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: deploy

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Read package.json version
        id: read_version
        run: |
          version=$(node -p "require('./package.json').version")
          major=$(echo $version | cut -d. -f1)
          minor=$(echo $version | cut -d. -f2)
          patch=$(echo $version | cut -d. -f3 | cut -d- -f1)
          new_version="${major}.${minor}.0"
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Setup EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO }}

      - name: 📦 Install dependencies
        run: npm install

      - name: Build Production AAB
        run: eas build --platform android --profile production
        env:
          VERSION: ${{ env.VERSION }}
